import esbuild from "esbuild";
import process from "process";
import { builtinModules } from 'node:module';
import { deployArtifacts } from "./deploy.mjs";

// 打包完成后把运行用文件同步到 vault 里的插件目录（源码只在本仓库）。
// 目标目录不存在时静默跳过 —— CI 上跑 build 不该因此失败。
const deployToPluginDir = {
	name: "deploy-to-plugin-dir",
	setup(build) {
		build.onEnd((result) => {
			if (result.errors.length > 0) return;
			deployArtifacts();
		});
	},
};

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
	plugins: [deployToPluginDir],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
